In [3]:
import numpy as np

# to declare a array using numpy
# a = np.array([1,2,3])
# b = np.array([4,5,6])


# print(a+b)
# to add two list
# [5,7,9]

# arr = np.array([10,20,30])
# print(arr) # [10,20,30]

arr2 = np.array([[1,2],[3,4]])
print(arr2)
# [[1,2]
#  [3,4]]

print(type(arr))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [ ]:
print(np.zeros(5))
# [0. 0. 0. 0. 0.]

print(np.ones(3))
# [1. 1. 1.]

print(np.arange(0,10))
# 1 to 9

print(np.linspace(0,1,5))
# 5 numbers between 0 and 1

In [2]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [4]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)
#[[1 2 3]
# [4 5 6]]

print(arr.shape)
# rows, columns
#(2, 3)

print(arr.size)
# to find total no. of elements
# 6

print(arr.ndim)
# to find no. of dimensions
# 2

print(arr.dtype)
# to find data type
# int64

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int64


In [5]:
a = np.array([1,2,3])

# to add any value to the list
print(a + 2)
# [3 4 5]

# to multiply any no. to the list
print(a * 3)
# [3 6 9]

# to find the square root
print(np.sqrt(a))
#[1.         1.41421356 1.73205081]

# to find the sum
print(np.sum(a))
# 6

# to calculate average
print(np.mean(a))
# 2.0


[3 4 5]
[3 6 9]
[1.         1.41421356 1.73205081]
6
2.0
