In [3]:
from math import factorial

# 1. Reverse string
str = 'Hari'
rev=''
for i in range(len(str),0,-1):
    rev += str[i-1]
print(rev)

iraH


In [12]:
# 2. Fibonacci series
num1 = 0
num2 = 1
for i in range(1,21):
    print(num1, end=" ")
    result = num1 + num2
    num1 = num2
    num2 = result


0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 

In [9]:
num = 5
factorial = 1
for i in range(1, num + 1):
    factorial = factorial * i
print("The factorial of", num, "is", factorial)

The factorial of 5 is 120


In [2]:
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

n = 20
primes = []
for num in range(2, n + 1):
    if is_prime(num):
        primes.append(num)
print(f'All prime numbers from 1 to {n}: {primes}')

All prime numbers from 1 to 20: [2, 3, 5, 7, 11, 13, 17, 19]


In [1]:
for i in range(2,20):
    if i <=3:
        print(i, end=" ")
    elif i % 2 != 0 or i % 3 != 0:
        continue


2 3 

In [5]:
s = "A man, a plan, a canal: Panama"
rev=""
sym = [',',':',' ']
cap = ['A','P']
for i in range(len(s)-1,-1,-1):
    if s[i] in sym:
        continue
    elif s[i] in cap:
        rev+=s[i].lower()
    else:
        rev+=s[i]
print(rev)

f=''
for i in s:
    if i in sym:
        continue
    elif i in cap:
        f+=i.lower()
    else:
        f+=i

print(f)

if rev == f:
    print(True)
else:
    print(False)

amanaplanacanalpanama
amanaplanacanalpanama
True


In [7]:
# 2. given an integer n, determine whether it is a power of two
n=16
num=2
for i in range(1,10):
    if num**i==n:
        print(True)
    else:
        continue


True


In [8]:
nums = [1,2,2,3,4,3,5]
n=[]
for i in nums:
    if i not in n:
        n+=[i]
print(n)

[1, 2, 3, 4, 5]


In [9]:
s='abcabcbb'
n=''
for i in s:
    if i not in n:
        n+=i

count=0
for j in n:
    count+=1
print(count)

3


In [11]:
stack = [1,2,3,4]
s=[]
for i in range(len(stack)-1,-1,-1):
    s+=[stack[i]]
print(s)

[4, 3, 2, 1]


In [2]:
def palindrome(str):
    rev=''
    for i in range(len(str)-1,-1,-1):
        rev+=str[i]
    if rev == str:
        return True
    else:
        return False
print(palindrome('mam'))
print(palindrome('madon'))
print(palindrome('pop'))
print(palindrome('sir'))

True
False
True
False


In [37]:
import numpy as np

# a = np.array([1,2,3])
# b = np.array([4,5,6])
# print(a+b) # [5,7,9]

# arr = np.array([10,20,30])
# print(arr) # [10,20,30]

arr2 = np.array([[1,2],[3,4]])
print(arr2) # [[1,2]
            #  [3,4]]

print(type(arr2))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2.4.2


In [17]:
print(np.zeros(5))# [0. 0. 0. 0. 0.]
print(np.ones(3))# [1. 1. 1.]
print(np.arange(0,10))# 1 to 9
print(np.linspace(0,1,5))# 5 numbers between 0 and 1

[0. 0. 0. 0. 0.]
[1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


In [19]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print(arr.shape)   # rows, columns
print(arr.size)    # total elements
print(arr.ndim)    # number of dimensions
print(arr.dtype)   # data type

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int64


In [31]:
arr = np.array([10,20,30,40,50])

print(arr[0])      # 10
print(arr[0:5])    # [20 30 40]

10
[10 20 30 40 50]


In [32]:
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr2[0,1])   # row 0, column 1

2


In [35]:
a = np.array([1,2,3])

print(a + 2)       # [3 4 5]
print(a * 3)       # [3 6 9]
print(np.sqrt(a))  # square root
print(np.sum(a))   # sum
print(np.mean(a))  # average

[3 4 5]
[3 6 9]
[1.         1.41421356 1.73205081]
6
2.0


In [50]:
# 1. Create a NumPy array containing numbers from 1 to 10.
a = np.arange(1,11)
print(a)

# 2. Create an array of 10 zeros.
n = np.zeros(10)
print(n)

# 3. Create an array of 5 ones.
n = np.ones(5)
print(n)

# 4. Create an array of numbers from 10 to 50.
n = np.arange(10,51)
print(n)

# 5. Create an array of even numbers from 2 to 20.
n = np.arange(2,20)
even = n[n % 2 == 0]
print(even)

# 6. Find the shape of the array.
a = np.shape(even)
print(a)

# 7. Find the number of dimensions.
a = np.ndim(arr2)
print(a)

# 8. Find the total number of elements.


[ 1  2  3  4  5  6  7  8  9 10]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[ 2  4  6  8 10 12 14 16 18]
(9,)
2


In [38]:
import time

startTime = time.time()

# write your code or functions calls

endTime = time.time()
totalTime = endTime - startTime

print("Total time required to execute code is= ", totalTime)

Total time required to execute code is=  3.62396240234375e-05


In [39]:
list1 = ['Scott', 'Eric', 'Kelly', 'Emma', 'Smith']
list2 = ['Scott', 'Eric', 'Kelly']

set1 = set(list1)
set2 = set(list2)

list3 = list(set1.symmetric_difference(set2))
print(list3)

['Smith', 'Emma']


In [1]:
# Bubble Sort
list = [19,2,31,45,6,11,121,27]
def bubblesort(list):
    for i in range(len(list)):
        for j in range(len(list)):
            if list[i]<list[j]:
                list[i],list[j] = list[j],list[i]
    return list

print(bubblesort(list))

[2, 6, 11, 19, 27, 31, 45, 121]


In [2]:
my_str = "Hello this Is an Example With cased letters"

words = [word.lower() for word in my_str.split()]

words.sort()

for i in words:
    print(i)

an
cased
example
hello
is
letters
this
with


In [6]:
n = 'madam'
def palin(n):
    rev=''
    for i in range(len(n)-1,-1,-1):
        rev+=n[i]
    return rev == n
print(palin(n))

True


In [7]:
n = 'madam'
def palin(n):
    left = 0
    right = len(n)-1
    while left < right:
        if n[left] != n[right]:
            return False
        left += 1
        right -= 1
    return True
print(palin(n))

False


In [11]:
# 3. Check if a Number is Prime

def prime(n):
    for i in range(2,n):
        for j in range(2,i):
            if i % j == 0:
                continue
            print(j)
prime(16)

2
3
2
3
4
4
5
2
3
4
5
6
3
5
6
7
2
4
5
6
7
8
3
4
6
7
8
9
2
3
4
5
6
7
8
9
10
5
7
8
9
10
11
2
3
4
5
6
7
8
9
10
11
12
3
4
5
6
8
9
10
11
12
13
2
4
6
7
8
9
10
11
12
13
14


In [15]:
# 4. Input: "programming"
n = "programming"
s = {}
for i in n:
    if i in s:
        s[i]+=1
    else:
        s[i] = 1
print(s)

from collections import Counter
print(Counter(n))

{'p': 1, 'r': 2, 'o': 1, 'g': 2, 'a': 1, 'm': 2, 'i': 1, 'n': 1}
Counter({'r': 2, 'g': 2, 'm': 2, 'p': 1, 'o': 1, 'a': 1, 'i': 1, 'n': 1})


In [17]:
n = [10, 5, 20, 8]

for i in range(len(n)-1,-1,-1):
    for j in range(len(n)-1,-1,-1):
        if n[i] < n[j]:
            n[i],n[j] = n[j],n[i]

print(n[1])

10


In [19]:
def sec(n):
    first = float('-inf')
    sec = float('-inf')
    for i in n:
        if i > first:
            sec = first
            first = i
        elif i > sec and i != first:
            sec = i
    return sec

print(sec(n))

10


In [22]:
k = [0,1,0,3,12]
pos = 0
for i in range(len(k)):
    if k[i] != 0:
        k[pos], k[i] = k[i], k[pos]
        pos+=1

print(k)

[1, 3, 12, 0, 0]


In [29]:
num = [2,7,11,15]
target = 9

def sum(num,target):
    for i in range(len(num)):
        for j in range(i,len(num)):
            if num[i] + num[j] == target:
                return [i,j]
print(sum(num,target))

[0, 1]


In [34]:
prices = [7,1,5,3,6,4]

def max_profit(prices):
    min_price = float('inf')
    max_profit = 0

    for price in prices:
        if price < min_price:
            min_price = price
        else:
            profit = price - min_price
            max_profit = max(max_profit, profit)
    return max_profit

print(max_profit(prices))


5


In [10]:
from datetime import datetime

class Recharge:
    def __init__(self, year, month, day, amount=299, validity_days=30):
        self.amount = amount
        self.validity_days = validity_days
        self.recharge_date = datetime(year, month, day)

    def calculate_details(self):
        today = datetime.today()
        total_days = (today - self.recharge_date).days

        if total_days < 0:
            return 0, 0

        # total amount spent till now
        cycles = total_days // self.validity_days + 1
        total_spent = cycles * self.amount

        # balance days in current cycle
        balance_days = self.validity_days - (total_days % self.validity_days)

        # if exactly completed cycle
        if total_days % self.validity_days == 0:
            balance_days = 0

        return balance_days, total_spent

recharge = Recharge(2026, 1, 1)

balance, spent = recharge.calculate_details()

print("Balance Days:", balance)
print("Total Amount Spent:", spent)

Balance Days: 6
Total Amount Spent: 598
